scene: stadium

robot: JR2_Kinova_Wrist
wheel_velocity: 0.1
arm_velocity: 0.05

task: reaching
fisheye: false

initial_pos: [0.0, 0.0, 0.0]
initial_orn: [0.0, 0.0, 0.0]

target_pos: [3.0, 0.0, 1.0]
target_orn: [0.0, 0.0, 0.0]

is_discrete: false
additional_states_dim: 20
goal_dim: 3

reward_type: l2
success_reward: 10.0
slack_reward: -0.01
potential_reward_weight: 5.0
collision_reward_weight: -0.1
collision_ignore_link_a_ids: []
collision_ignore_body_b_ids: [1,3]
max_collisions_allowed: 0


discount_factor: 0.99

dist_tol: 0.06
max_step: 20

output: [sensor, goal]
resolution: 256
fov: 1.57

use_filler: true
display_ui: false
show_diagnostics: false
ui_num: 2
ui_components: [RGB_FILLED, DEPTH]

speed:
  timestep: 0.001
  frameskip: 10

mode: web_ui
verbose:
fast_lq_render: true

visual_object_at_initial_target_pos: true
target_visual_object_visible_to_agent: true

debug: false