scene: stadium

robot: JR2_Kinova_Head
wheel_velocity: 0.4
head_velocity: 0.0
arm_velocity: 0.4

task: pointgoal            # pointgoal or reaching
num_obstacles: 0          # number of obstacles, 0 or 2
obstacle_type: block      # block or realistic
dist_tol: 0.5             # 0.1 for reaching, 0.5 for pointgoal
max_step: 200

fisheye: false

initial_pos: [0.0, 0.0, 0.0]
initial_orn: [0.0, 0.0, 0.0]

target_pos: [4.0, 0.0, 0.0]
target_orn: [0.0, 0.0, 0.0]

is_discrete: false
base_proprioceptive_states_dim: 5
goal_dim: 3

reward_type: l2
success_reward: 30.0
slack_reward: -0.01
potential_reward_weight: 5.0
collision_reward_weight: -5.0
collision_ignore_link_a_ids: []
collision_ignore_body_b_ids: [1,3]
max_collisions_allowed: 0

discount_factor: 0.99

# output: [base_proprioceptive, arm_proprioceptive, goal, rgb, depth, seg, wrist_rgb, wrist_depth, wrist_seg, last_camera_mask_indices]
output: [base_proprioceptive, depth]

resolution: 256
vertical_fov: 75

use_filler: true
display_ui: false
show_diagnostics: false
ui_num: 2
ui_components: [RGB_FILLED, DEPTH]

speed:
  timestep: 0.001
  frameskip: 10

mode: web_ui
verbose:
fast_lq_render: true

visual_object_at_initial_target_pos: true
target_visual_object_visible_to_agent: true

debug: false
